name: Format

on: push

jobs:
  format-code:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: run script
        run: |
          python sitemap.py
      - name: commit sitemap
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update sitemap
          file_pattern: 'docs/sitemap.txt'
          skip_fetch: true
          skip_checkout: true